spring:
  application:
    name: Todo-App

  mvc:
    servlet:
      path: /api/v1/

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

security:
  jwt:
    secret-key: secret
    expiration-time: 259200000