CREATE TABLE my_user
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email        VARCHAR(255),
    password     VARCHAR(255),
    full_name    VARCHAR(255),
    age          VARCHAR(255),
    about        VARCHAR(255),
    gender       VARCHAR(255),
    is_not_block BOOLEAN,
    CONSTRAINT pk_my_user PRIMARY KEY (id)
);

CREATE TABLE todo
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(100)                            NOT NULL,
    description  VARCHAR(255)                            NOT NULL,
    is_completed BOOLEAN,
    user_id      BIGINT,
    CONSTRAINT pk_todo PRIMARY KEY (id)
);

ALTER TABLE todo
    ADD CONSTRAINT FK_TODO_ON_USER FOREIGN KEY (user_id) REFERENCES my_user (id);