CREATE TABLE premium
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_at TIMESTAMP WITHOUT TIME ZONE,
    end_at   TIMESTAMP WITHOUT TIME ZONE,
    user_id  BIGINT,
    CONSTRAINT pk_premium PRIMARY KEY (id)
);

ALTER TABLE my_user
    ADD todo_limit BIGINT;

ALTER TABLE premium
    ADD CONSTRAINT uc_premium_user UNIQUE (user_id);

ALTER TABLE premium
    ADD CONSTRAINT FK_PREMIUM_ON_USER FOREIGN KEY (user_id) REFERENCES my_user (id);